[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "unsloth"
dynamic = ["version", "dependencies"]
description = "2X faster LLM finetuning"
readme = "README.md"
requires-python = ">=3.9"
license = {file = "LICENSE"}
keywords = ["ai", "llm",]
authors = [
	{email = "info@unsloth.ai"},
	{name = "Unsloth AI team"},
]
maintainers = [
 	{name = "Daniel Han", email = "danielhanchen@gmail.com"},
 	{name = "Michael Han", email = "info@unsloth.ai"},
]
classifiers = [
 	"Programming Language :: Python",
]

[tool.setuptools.dynamic]
version = {attr = "unsloth.__version__"}
dependencies = {file = ["requirements.txt"]}
optional-dependencies = {
	cu118 = { file = ["requirements_cu118.txt"] },
	cu121 = { file = ["requirements_cu121.txt"] },
}

[project.urls]
homepage = "http://www.unsloth.ai"
documentation = "https://github.com/unslothai/unsloth"
repository = "https://github.com/unslothai/unsloth"